version: 0.0
os: linux
files:
  - source: /target/SampleJenkinsAwsDeployApp.war
    destination: /var/lib/tomcat8/webapps
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 180
      runas: root

